version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    labels:
      - "PR Type: Maintenance"
    pull-request-branch-name:
      separator: "-"
